#!/usr/bin/env bash
echo "==create-bucket=="

#check if bucket name is provided
if [ -z "$1" ]; then
    echo "There need to be a bucket name provided as the first argument. e.g., ./
    create-bucket my-bucket-name us-west-2"
    exit 1
fi

if [ "$REGION" = "us-east-1" ]; then
    aws s3api create-bucket \
        --bucket "$BUCKET" \
        --region us-east-1
else
    aws s3api create-bucket \
        --bucket "$BUCKET" \
        --region "$REGION" \
        --create-bucket-configuration LocationConstraint="$REGION"
fi

echo "Bucket $BUCKET created successfully in $REGION."