#!/usr/bin/env bash

echo "==list-objects=="

#check if bucket name is provided
if [ -z "$1" ]; then
    echo "There need to be a bucket name provided as the first argument. e.g., ./
    create-bucket my-bucket-name us-west-2"
    exit 1
fi

aws s3api list-objects \
--bucket "$1" \
--output text \

# echo "Bucket $1 created successfully."
